=== chungeric/WSD-Group-Assignment/web/WEB-INF/tutors.xsd
<?xml version="1.0"?>
<xs:schema
 xmlns:xs="http://www.w3.org/2001/XMLSchema"
 elementFormDefault="qualified">
    
    <xs:simpleType name="name">
        <xs:restriction base="xs:string">
            <xs:pattern value="([A-Z][a-z]+\s)+([A-Z][a-z]+)"/>            
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="email">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z\._]+[@]([a-z-]+)([\.][a-z-]+)+"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="password">
        <xs:restriction base="xs:string">
            <xs:pattern value=".{6,}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="dob">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{1,2}/\d{1,2}/\d{1,4}"/>
        </xs:restriction>
    </xs:simpleType>
    
    
    <xs:element name="tutors">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tutor" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="name"/>
                            <xs:element name="email" type="email"/>
                            <xs:element name="password" type="password"/>
                            <xs:element name="dob" type="dob"/>
                            <xs:element name="userType" type="xs:string"/>
                            <xs:element name="subject" type="xs:string"/>     
                            <xs:element name="status" type="xs:string"/>       
                        </xs:sequence>             
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== chungeric/WSD-Group-Assignment/web/WEB-INF/tutors.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl href="WEB-INF/tutors.xsl"?>
<tutors
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="tutors.xsd"> 
<!--<tutors>-->
        <tutor>
            <name>Chris Burney</name>
            <email>chrisburney@tutor.com</email>
            <password>password</password>
            <dob>1968-11-02</dob>
            <userType>Tutor</userType>
            <subject>WSD</subject>
            <status>Available</status>
        </tutor>

        <tutor>
            <name>Selina Madrid</name>
            <email>smadrid@tutor.com</email>
            <password>password123</password>
            <dob>1986-04-29</dob>
            <userType>Tutor</userType>
            <subject>USP</subject>
            <status>Available</status>
        </tutor>

        <tutor>
            <name>Maxwell Parra</name>
            <email>maxparra@tutor.com</email>
            <password>password123</password>
            <dob>1970-08-12</dob>
            <userType>Tutor</userType>
            <subject>SEP</subject>
            <status>Available</status>
        </tutor>

        <tutor>
            <name>Jonah Stockton</name>
            <email>jstockton@tutor.com</email>
            <password>password123</password>
            <dob>1979-09-09</dob>
            <userType>Tutor</userType>
            <subject>AppProg</subject>
            <status>Available</status>
        </tutor>

        <tutor>
            <name>Martin Silver</name>
            <email>martinsilver@tutor.com</email>
            <password>password123</password>
            <dob>1985-10-22</dob>
            <userType>Tutor</userType>
            <subject>MobileApp</subject>
            <status>Available</status>
        </tutor>
    
</tutors>
